clientes/urls.py
from django.urls import path, include
from .views import ClienteCreate, ClienteUpdate, ClienteList, ClienteListAPI

urlpatterns = [
    path('adicionar/', ClienteCreate.as_view(), name='cliente-adicionar'),
    path('alterar/<int:pk>/', ClienteUpdate.as_view(), name='cliente-alterar'),
    path('pesquisar/', ClienteList.as_view(), name='cliente-pesquisar'),
    path('', ClienteListAPI.as_view())
]

easy2make/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('estoque/', include(('estoque.urls', 'estoque'), namespace='estoque')),
    path('clientes/', include(('clientes.urls', 'clientes'), namespace='clientes')),
    path('vendas/', include(('vendas.urls', 'vendas'), namespace='vendas')),
    path('auth/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

estoque/urls.py
from django.urls import path, include
from .views import ProdutoListAPI, ProdutoCreate, ProdutoUpdate, ProdutoList, CategoriaCreate, CategoriaUpdate, CategoriaList

urlpatterns = [
    path('produto/adicionar/', ProdutoCreate.as_view(), name='produto-adicionar'),
    path('produto/<int:pk>/', ProdutoUpdate.as_view(), name='produto-alterar'),
    path('produto/pesquisar/', ProdutoList.as_view(), name='produto-pesquisar'),
    path('produtos/', ProdutoListAPI.as_view()),
    path('categoria/adicionar/', CategoriaCreate.as_view(), name='categoria-adicionar'),
    path('categoria/<int:pk>/', CategoriaUpdate.as_view(), name='categoria-alterar'),
    path('categoria/pesquisar/', CategoriaList.as_view(), name='categoria-pesquisar')
]

vendas/urls.py
from django.urls import path, include
from .views import VendaList, VendaCreateForm, VendaDetail, VendaCupomDetail, VendaUpdateAPI, ItemVendaUpdateAPI, ItemVendaDeleteAPI, VendaCreateAPI, ItemVendaCreateAPI, VendaDeleteAPI

urlpatterns = [
    path('', VendaCreateForm.as_view(), name='vendas-create-form'),
    path('pesquisar/', VendaList.as_view(), name='vendas-pesquisar'),
    path('<int:pk>/', VendaDetail.as_view(), name='vendas-detalhe'),
    path('<int:pk>/cupom/', VendaCupomDetail.as_view()),
    path('adicionar/', VendaCreateAPI.as_view()),
    path('remover/<int:pk>/', VendaDeleteAPI.as_view()),
    path('alterar/<int:pk>/', VendaUpdateAPI.as_view()),
    path('itens/adicionar/', ItemVendaCreateAPI.as_view()),
    path('itens/remover/<int:pk>/', ItemVendaDeleteAPI.as_view()),
    path('itens/alterar/<int:pk>/', ItemVendaUpdateAPI.as_view())
]

easy2make/templates/base.html
<html style="max-width:100%; overflow-x:hidden">

    <head>
        {% load bootstrap3 %}
        {% bootstrap_css %}
        {% bootstrap_javascript jquery=True %}
        {% load static %}
        
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" media="screen">   
        <link type="text/css" href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" >
        <link type="text/css" href="{% static 'css/fonts.css' %}" rel="stylesheet">
        <link rel="shortcut icon" href="{%  static 'assets/logo.ico' %}">

        <title>Easy2Make</title>
    </head>
    
    {% block bootstrap3_content %}
    <body>
        <main>    
            <div class="row">
                
                <aside class="col-md-3">
                    <div class="nav-side-menu">
                        <div class="brand">Easy2Make</div>
                        
                        <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
                        
                        <div class="menu-list">
                            
                            <ul id="menu-content" class="menu-content collapse out">
                                
                                <li  data-toggle="collapse" data-target="#estoque" class="collapsed active">
                                    <a href="#"><i class="fa fa-wrench fa-lg"></i> Estoque <span class="arrow"></span></a>
                                </li>
                                
                                <ul class="sub-menu collapse" id="estoque">
                                    <li><a href="{% url 'estoque:produto-pesquisar' %}">Produtos</a></li>
                                    <li><a href="{% url 'estoque:categoria-pesquisar' %}">Categorias</a></li>
                                </ul>
                                
                                <li  data-toggle="collapse" data-target="#clientes" class="collapsed active">
                                    <a href="#"><i class="fa fa-users fa-lg"></i> Clientes <span class="arrow"></span></a>
                                </li>
                                
                                <ul class="sub-menu collapse" id="clientes">
                                    <li><a href="{% url 'clientes:cliente-pesquisar' %}">Pesquisar</a></li>
                                </ul>    

                                <li  data-toggle="collapse" data-target="#vendas" class="collapsed active">
                                        <a href="#"><i class="fa fa-shopping-cart fa-lg"></i> Vendas <span class="arrow"></span></a>
                                </li>
                                    
                                <ul class="sub-menu collapse" id="vendas">
                                    <li><a href="{% url 'vendas:vendas-create-form' %}">Cadastrar</a></li>
                                    <li><a href="{% url 'vendas:vendas-pesquisar' %}">Pesquisar</a></li>
                                </ul>

                                <li  class="collapsed active">
                                        <a href="{% url 'logout' %}"><i class="fa fa-power-off fa-lg"></i> Sair </span></a>
                                </li>
    
                                <div>
                                    
                                    <img height="300" width="299" src="{% static 'assets/logo.jpg' %}">
                                    
                                </div>
                            </ul>            
                        </div>
                    </div>                                        
                </aside>
                            
                <article class="col-md-8" style="margin-top:15px">
                    {% if messages %}
                    <div class="row">
                        <div class="alert alert-success">
                            <button class="close" data-dismiss="alert">×</button> 
                            {% for m in messages%}
                            <li>{{m}}</li>
                            {% endfor%}
                        </div>
                    </div>
                    {% endif %}
                    
                    {% block content %}
                    
                    {% endblock %}
                    
                </article>
            </div>
        </main>
                    
    </body>
    {% endblock %}
</html>

easy2make/templates/paginated.html
{% if is_paginated %}
<ul class="pagination pagination-centered">
    {% if page_obj.has_previous %}
        <li><a href="?page=1"><<</a></li>
        <li><a href="?page={{ page_obj.previous_page_number }}"><</a></li>
    {% endif %}

    {% for i in paginator.page_range %}
        <li {% if page_obj.number == i %} class="active" {% endif %}><a href="?page={{i}}">{{i}}</a></li>
    {% endfor %}

    {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">></a></li>
        <li><a href="?page={{ page_obj.paginator.num_pages }}">>></a></li>
    {% endif %}
</ul>
{% endif %}