clientes/urls.py
from django.urls import path, include
from .views import ClienteCreate, ClienteUpdate, ClienteList, ClienteListAPI

urlpatterns = [
    path('adicionar/', ClienteCreate.as_view(), name='cliente-adicionar'),
    path('alterar/<int:pk>/', ClienteUpdate.as_view(), name='cliente-alterar'),
    path('pesquisar/', ClienteList.as_view(), name='cliente-pesquisar'),
    path('', ClienteListAPI.as_view())
]

easy2make/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('estoque/', include(('estoque.urls', 'estoque'), namespace='estoque')),
    path('clientes/', include(('clientes.urls', 'clientes'), namespace='clientes')),
    path('vendas/', include(('vendas.urls', 'vendas'), namespace='vendas')),
    path('auth/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

vendas/urls.py
from django.urls import path, include
from .views import VendaList, VendaCreateForm, VendaDetail, VendaCupomDetail, VendaUpdateAPI, ItemVendaUpdateAPI, ItemVendaDeleteAPI, VendaCreateAPI, ItemVendaCreateAPI, VendaDeleteAPI

urlpatterns = [
    path('', VendaCreateForm.as_view(), name='vendas-create-form'),
    path('pesquisar/', VendaList.as_view(), name='vendas-pesquisar'),
    path('<int:pk>/', VendaDetail.as_view(), name='vendas-detalhe'),
    path('<int:pk>/cupom/', VendaCupomDetail.as_view()),
    path('adicionar/', VendaCreateAPI.as_view()),
    path('remover/<int:pk>/', VendaDeleteAPI.as_view()),
    path('alterar/<int:pk>/', VendaUpdateAPI.as_view()),
    path('itens/adicionar/', ItemVendaCreateAPI.as_view()),
    path('itens/remover/<int:pk>/', ItemVendaDeleteAPI.as_view()),
    path('itens/alterar/<int:pk>/', ItemVendaUpdateAPI.as_view())
]

vendas/models.py
from django.db import models
from estoque.models import Produto
from clientes.models import Cliente
from .choices import VENDA_SITUACAO_CHOICES
import datetime

class Venda(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, related_name='compras')
    data = models.DateField(blank=True, null=True)
    situacao = models.CharField(max_length=1, blank=False, default='P', choices=VENDA_SITUACAO_CHOICES)
    total = models.DecimalField(max_digits=10, decimal_places=2, null=True)

class ItemVenda(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    venda = models.ForeignKey(Venda, on_delete=models.CASCADE, related_name='itens')
    quantidade = models.PositiveIntegerField(blank=False, default=1)

vendas/forms.py
from django.forms import ModelForm, DateField
from .models import Venda, ItemVenda
from django.forms.widgets import DateInput

class VendaForm(ModelForm):
    class Meta:
        model = Venda
        fields = ['cliente']

class VendaSearchForm(ModelForm):

    data_inicio = DateField(label='Data inicial', required=False, input_formats=['%Y-%m-%d'], widget=DateInput(attrs={'type': 'date'}))
    data_fim = DateField(label='Data final', required=False, input_formats=['%Y-%m-%d'], widget=DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Venda
        fields = ['situacao']

class ItemVendaForm(ModelForm):
    class Meta:
        model = ItemVenda
        fields = ['produto','venda']

class ItemVendaUpdateForm(ModelForm):
    class Meta:
        model = ItemVenda
        fields = ['quantidade']

vendas/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView, View, DetailView
from json_views.views import JSONFormView
from search_views.search import SearchListView
from search_views.filters import BaseFilter
from .forms import VendaForm, ItemVendaForm, ItemVendaUpdateForm, VendaSearchForm
from .models import Venda, ItemVenda
import datetime
import json
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

class VendaFilter(BaseFilter):
    search_fields = {
        'situacao' : ['situacao'],
        'data_inicio' :{ 'operator' : '__gte', 'fields':['data']},
        'data_fim' :{ 'operator' : '__lte', 'fields':['data']}          
    }


class VendaList(SearchListView):
    model = Venda
    template_name = 'pesquisar_venda_form.html'
    paginate_by = 8
    form_class = VendaSearchForm
    filter_class = VendaFilter

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return __dispatch__(self, VendaList, *args, **kwargs)

class VendaCreateForm(TemplateView):
    template_name = 'vendas_form.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return __dispatch__(self, VendaCreateForm, *args, **kwargs)

class VendaDetail(DetailView):
    model = Venda
    template_name = 'vendas_detalhe.html'
    
    def get_object(self):
        return __get_object__(self, VendaDetail)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return __dispatch__(self, VendaDetail, *args, **kwargs)

class VendaCupomDetail(DetailView):
    model = Venda
    template_name = 'cupom_template.html'

    def get_object(self):
        return __get_object__(self, VendaCupomDetail)
    
    def get_context_data(self, **kwargs):
        context = super(VendaCupomDetail, self).get_context_data(**kwargs)
        venda = super(VendaCupomDetail, self).get_object()
        venda.total = 0
        
        items = []
        for item in venda.itens.all():
            item.total = 0
            item.total = item.quantidade * item.produto.preco
            venda.total += item.total
            items.append(item)
        
        context['items'] = items
        return context

class VendaCreateAPI(JSONFormView):
   
    form_class = VendaForm
    def post(self, request, *args, **kwargs):
        return __post__(self, VendaCreateAPI, request, args, kwargs)

class VendaDeleteAPI(JSONFormView):

    form_class = VendaForm    
    def post(self, request, *args, **kwargs):
        venda = Venda.objects.get(pk=kwargs['pk'])
        venda.delete()
        return self.render_to_response(self.get_context_data(sucess=True))

class VendaUpdateAPI(View):
 
    def post(self, request, *args, **kwargs):
        venda = Venda.objects.get(pk=kwargs['pk'])
        venda.situacao = 'F'
        venda.data = datetime.datetime.now()
        venda.total = 0

        for item in venda.itens.all():
            produto = item.produto
            produto.quantidade -= item.quantidade
            venda.total += item.quantidade * item.produto.preco
            produto.save()
        
        venda.save()
        
        return HttpResponse(json.dumps({'sucess':True}))

class ItemVendaCreateAPI(JSONFormView):
   
    form_class = ItemVendaForm
    def post(self, request, *args, **kwargs):
        return __post__(self, ItemVendaCreateAPI, request, args, kwargs)

class ItemVendaDeleteAPI(JSONFormView):

    form_class = ItemVendaForm
    def post(self, request, *args, **kwargs):
        item = ItemVenda.objects.get(pk=kwargs['pk'])
        item.delete()
        return self.render_to_response(self.get_context_data(sucess=True))

class ItemVendaUpdateAPI(JSONFormView):

    form_class = ItemVendaUpdateForm
    def post(self, request, *args, **kwargs):
        item = ItemVenda.objects.get(pk=kwargs['pk'])
        form = self.form_class(request.POST, instance=item)
        form.save()
        return self.render_to_response(self.get_context_data(sucess=True))

def __post__(self, classView, request, args, kwargs):
    
    form = self.form_class(request.POST)
    if form.is_valid():
        return self.render_to_response(self.get_context_data(id=form.save().id, sucess=True))
    return super(classView, self).post(self, request, args, kwargs)

def __get_object__(self, classView):
    
    venda = super(classView, self).get_object()
    # caso a venda não esteja finalizada
    if venda.situacao == 'P':
        venda.total = 0
        for item in venda.itens.all():
            venda.total += (item.quantidade * item.produto.preco)
    
    return venda

def __dispatch__(self, classView, *args, **kwargs):
    return super(classView, self).dispatch( *args, **kwargs)

vendas/templates/cupom_template.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/recibo.css' %}" type="text/css" media="print">

<table class="printer-ticket">
    
    <thead>
       <tr>
           <th class="title" colspan="3">GO TEC! Acessórios</th>
       </tr>
       <tr>
           <th colspan="3">{{venda.data | date:'d/m/y' }}</th>
       </tr>
       <tr>
           <th colspan="3">
               Cliente <br />
               {{ venda.cliente.nome }}
           </th>
       </tr>
       <tr>
           <th class="ttu" colspan="3">
               <b>Cupom não fiscal</b>
           </th>
       </tr>
    </thead>
   
    <tbody>

    {% for item in items %}
        <tr class="top">
           <td colspan="3">{{item.produto.descricao}}</td>
        </tr>
        <tr>
           <td>R${{item.produto.preco}}</td>
           <td>{{item.quantidade | floatformat:2}}</td>
           <td>R${{item.total | floatformat:2}}</td>
        </tr>
    {% endfor %}

    </tbody>
   
    <tfoot>
       
    <tr class="ttu">
           <td colspan="2"><b>TOTAL</b></td>
           <td align="right">R${{venda.total | floatformat:2}}</td>
       </tr>
       
       <tr class="sup">
           <td colspan="3" align="center">
               easy2make
           </td>
       </tr>
    </tfoot>

</table>

vendas/templates/pesquisar_venda_form.html
{% extends 'easy2make/templates/base.html' %}

{% load bootstrap3 %}
{% load static %}

{% block content %}

    <div class="row" style="padding-bottom: 1rem;">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Vendas</a></li>
            <li class="breadcrumb-item"><a href="#">Pesquisar</a></li>
        </ol>
    </div>
    
    <form action="{% url 'vendas:vendas-pesquisar' %}" role="form" method="get">
        {% csrf_token %}
        
        
        {% for field in form %}
            {% bootstrap_field field %}
        {% endfor %}

        {% buttons %}
            {% bootstrap_button "Pesquisar" button_type="submit" button_class="btn-primary" %}
        {% endbuttons %}

    </form>

    {% if object_list %}
    
        <table class="table table-bordered">
            <tr>
                <th>Data</th>
                <th>Situação</th>
                <th>Cliente</th>
                <th></th>
            </tr>
            {% for object in object_list %}
            <tr>
                <td>
                    {% if object.data %}
                        {{object.data}}
                    {% endif %}
                </td>
                <td>
                    
                    {% if object.situacao == 'P' %}
                        Pendente
                    {% else %}
                        Finalizada
                    {% endif %}

                </td>
                <td>{{object.cliente.nome}}</td>
                <td>
                    <a href="{% url 'vendas:vendas-detalhe' object.id %}">
                        Detalhes
                    </a>
                </td>  
            </tr>
            {% endfor %}
        </table>

    {% endif %}

    {% include 'easy2make/templates/paginated.html' %}


{% endblock %}

vendas/templates/vendas_detalhe.html
{% extends 'easy2make/templates/base.html' %}

{% load bootstrap3 %}
{% load static %}
{% load mathfilters %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">

<div class="row" style="padding-bottom: 1rem;">
        <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'clientes:cliente-pesquisar' %}">Clientes</a></li>
                <li class="breadcrumb-item"><a href="{% url 'clientes:cliente-alterar' venda.cliente.id %}">{{venda.cliente.nome}}</a></li>
                <li class="breadcrumb-item"><a href="#">Compra {{venda.id}}</a></li>
        </ol>
</div>

<form action="#" role="form">       
    {% csrf_token %}
    <input type="hidden" id="id_venda" value="{{venda.id}}">
    <div class="form-group">
        <label class="control-label" for="cliente">Cliente</label>
        <input readonly type="text" name="cliente" maxlength="255" class="form-control" placeholder="Cliente" title="" required="" id="cliente">
    </div>
    
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Telefone</th>
                <th style="text-align:right"></th>
            </tr>
        </thead>
        <tbody id="tbody-cliente">

            <tr>
                <td>{{venda.cliente.nome}}</td>
                <td>{{venda.cliente.telefone}}</td>
                
                <td style="text-align: right;">
                    {% if venda.situacao == 'P' %}    
                        <i class="fa fa-trash cliente-remove" style="cursor: pointer;"></i>
                    {% endif %}
                </td>
            
            </tr>
            
        </tbody>
    </table>
    
    <div class="form-group">
        <label class="control-label" for="descricao">Produto</label>
        <input type="text" name="descricao"  maxlength="255" class="form-control" placeholder="Produto" title="" required="" id="descricao">
    </div>
    
    <table class="table table-striped table-sm">
        <thead class="black white-text">
            <tr><th colspan="3">Produtos</th></tr>
            <tr>
                <th>Descrição</th>
                <th>Preço Atual</th>
                <th>Estoque</th>
                <th class="col-sm-1" >Quantidade</th>
                <th class="col-sm-1"></th>
            </tr>
        </thead>
        <tbody id="tbody-produto">
            
        {% for item in venda.itens.all %}
            <tr id="{{item.id}}">
                <td>{{item.produto.descricao}}</td>
                <td>{{item.produto.preco | floatformat:2}}</td>
                
                
                {% if venda.situacao == 'P' %}

                    <td estoque="{{item.produto.quantidade}}">
                        
                        {% if item.produto.quantidade > item.quantidade %}
                            {{item.produto.quantidade|sub:item.quantidade }}
                        {% else %}
                            {{item.produto.quantidade}}
                        {% endif %}    

                    </td>
                    
                    {% with ''|center:item.produto.quantidade as range %}
                    <td>
                        
                        {% if item.produto.quantidade < item.quantidade %}

                            <label>Quantidade ({{item.quantidade}}) não está mais disponvél no estoque </label>

                        {% else %}
                            
                            <select class="form-control">
                                {% for _ in range %}
                                    <option 
                                        {% if forloop.counter == item.quantidade %}
                                            selected
                                        {% endif %}    
                                    value="{{ forloop.counter }}">{{ forloop.counter }}</option>
                                {% endfor %}
                            </select>

                        {% endif %}
                    
                    </td>
                    {% endwith %}
                
                    <td style="text-align: right;">
                        <i class="fa fa-trash produto-remove" style="cursor: pointer;"></i>
                    </td>
                
                {% else %}
                
                <td></td>

                <td>        
                    <select class="form-control" disabled>
                            <option>{{item.quantidade}}</option>
                    </select>                    
                </td>

                <td></td>

                {% endif %}

            </tr>
        {% endfor %}

        </tbody>
    </table>
    <hr>
    <div class="pull-right">
        <label id="total">Total: R$ {{venda.total}}</label>
    </div>
    
    {% if venda.situacao == 'P' %}
        <input type="button" id="btn-finalizar" value="Finalizar Venda" class="btn btn-primary">
        <input style="display:none" type="button" id="btn-cupom" value="Imprimir Cupom" class="btn btn-primary">
    {% else %}
        <input type="button" id="btn-cupom" value="Imprimir Cupom" class="btn btn-primary">
    {% endif %}


</form>

<script type="text/javascript" src="{%  static 'js/printThis.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/vendas.js' %}"></script> 


{% endblock %}

vendas/templates/vendas_form.html
{% extends 'easy2make/templates/base.html' %}

{% load bootstrap3 %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
<script type="text/javascript" src="{%  static 'js/printThis.js' %}"></script>

<div class="row" style="padding-bottom: 1rem;">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Vendas</a></li>
        <li class="breadcrumb-item"><a href="#">Cadastrar</a></li>
    </ol>
</div>

<form action="#" role="form">       
    {% csrf_token %}
    <input type="hidden" id="id_venda">
    <div class="form-group">
        <label class="control-label" for="cliente">Cliente</label>
        <input type="text" name="cliente" maxlength="255" class="form-control" placeholder="Cliente" title="" required="" id="cliente">
    </div>
    
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Telefone</th>
                <th style="text-align:right"></th>
            </tr>
        </thead>
        <tbody id="tbody-cliente">

        </tbody>
    </table>

    <div class="form-group">
            <label class="control-label" for="descricao">Produto</label>
            <input type="text" name="descricao" readonly maxlength="255" class="form-control" placeholder="Produto" title="" required="" id="descricao">
    </div>

    <table class="table table-striped table-sm">
            <thead class="black white-text">
                <tr><th colspan="3">Produtos</th></tr>
                <tr>
                    <th>Descrição</th>
                    <th>Preço Atual</th>
                    <th>Estoque</th>
                    <th class="col-sm-1" >Quantidade</th>
                    <th class="col-sm-1"></th>
                </tr>
            </thead>
            <tbody id="tbody-produto">

            </tbody>
    </table>
    <hr>
    <div class="pull-right">
        <label id="total">Total: R$ 0.00</label>
    </div>
    
    <input type="button" id="btn-finalizar" value="Finalizar Venda" class="btn btn-primary">
    <input style="display:none" type="button" id="btn-cupom" value="Imprimir Cupom" class="btn btn-primary">


</form>

<script type="text/javascript" src="{%  static 'js/printThis.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/vendas.js' %}"></script> 
    
    
{% endblock %}