easy2make/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('estoque/', include(('estoque.urls', 'estoque'), namespace='estoque')),
    path('clientes/', include(('clientes.urls', 'clientes'), namespace='clientes')),
    path('vendas/', include(('vendas.urls', 'vendas'), namespace='vendas')),
    path('auth/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

estoque/urls.py
from django.urls import path, include
from .views import ProdutoListAPI, ProdutoCreate, ProdutoUpdate, ProdutoList, CategoriaCreate, CategoriaUpdate, CategoriaList

urlpatterns = [
    path('produto/adicionar/', ProdutoCreate.as_view(), name='produto-adicionar'),
    path('produto/<int:pk>/', ProdutoUpdate.as_view(), name='produto-alterar'),
    path('produto/pesquisar/', ProdutoList.as_view(), name='produto-pesquisar'),
    path('produtos/', ProdutoListAPI.as_view()),
    path('categoria/adicionar/', CategoriaCreate.as_view(), name='categoria-adicionar'),
    path('categoria/<int:pk>/', CategoriaUpdate.as_view(), name='categoria-alterar'),
    path('categoria/pesquisar/', CategoriaList.as_view(), name='categoria-pesquisar')
]

vendas/urls.py
from django.urls import path, include
from .views import VendaList, VendaCreateForm, VendaDetail, VendaCupomDetail, VendaUpdateAPI, ItemVendaUpdateAPI, ItemVendaDeleteAPI, VendaCreateAPI, ItemVendaCreateAPI, VendaDeleteAPI

urlpatterns = [
    path('', VendaCreateForm.as_view(), name='vendas-create-form'),
    path('pesquisar/', VendaList.as_view(), name='vendas-pesquisar'),
    path('<int:pk>/', VendaDetail.as_view(), name='vendas-detalhe'),
    path('<int:pk>/cupom/', VendaCupomDetail.as_view()),
    path('adicionar/', VendaCreateAPI.as_view()),
    path('remover/<int:pk>/', VendaDeleteAPI.as_view()),
    path('alterar/<int:pk>/', VendaUpdateAPI.as_view()),
    path('itens/adicionar/', ItemVendaCreateAPI.as_view()),
    path('itens/remover/<int:pk>/', ItemVendaDeleteAPI.as_view()),
    path('itens/alterar/<int:pk>/', ItemVendaUpdateAPI.as_view())
]

estoque/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator

class Categoria(models.Model):
    descricao = models.CharField(max_length=255, null=False)
    def get_absolute_url(self):
        return reverse('estoque:categoria-pesquisar')
    
    def __str__(self):
        return u'{0}'.format(self.descricao)
    
    class Meta:
        unique_together = ('descricao',)

class Produto(models.Model):
    descricao = models.CharField(max_length=255, null=False)
    preco = models.DecimalField(max_digits=10, decimal_places=2, null=False)
    marca = models.CharField(max_length=255, blank=True, default='')
    quantidade = models.IntegerField(null=False, default=0, validators=[MinValueValidator(0)])
    modelo = models.CharField(max_length=255, blank=True, default='')
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('estoque:produto-pesquisar')

estoque/forms.py
from django.forms import ModelForm, ModelChoiceField
from django import forms
from .models import Produto, Categoria

class ProdutoForm(ModelForm):
    class Meta:
        model = Produto
        categoria = ModelChoiceField(queryset=Categoria.objects.all(),to_field_name="categoria", required=True)  
        fields = ['descricao','categoria','quantidade','preco', 'marca', 'modelo']

class ProdutoListForm(ModelForm):
    class Meta:
        model = Produto
        fields = ['descricao']

    

estoque/views.py
from django.shortcuts import render, reverse
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from search_views.search import SearchListView
from search_views.filters import BaseFilter
from .models import Produto, Categoria
from .forms import ProdutoForm, ProdutoListForm
from json_views.views import JSONListView
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

class ProdutoCreate(SuccessMessageMixin, CreateView):
    model = Produto
    form_class = ProdutoForm
    template_name = 'adicionar_produto_form.html'
    success_message = 'Produto cadastrado com sucesso!'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return __dispatch__(self, ProdutoCreate, *args, **kwargs)       

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return super(ProdutoCreate, self).form_valid(form)
        else:
            return render(request, self.template_name, {'form': form})

class ProdutoUpdate(SuccessMessageMixin, UpdateView):
    model = Produto
    form_class = ProdutoForm
    template_name = 'detalhe_produto_form.html'
    success_message = 'Produto alterado com sucesso!'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return __dispatch__(self, ProdutoUpdate, *args, **kwargs)
    
    def get_success_url(self):
        return reverse('estoque:produto-alterar', kwargs=self.kwargs)


class ProdutoFilter(BaseFilter):
    search_fields = {
        'descricao' : ['descricao'],          
    }

class ProdutoList(SearchListView):
    model = Produto
    template_name = 'pesquisar_produto_form.html'
    paginate_by = 8
    form_class = ProdutoListForm
    filter_class = ProdutoFilter

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return __dispatch__(self, ProdutoList, *args, **kwargs)

class ProdutoListAPI(JSONListView):
    model = Produto
    
    def post(self, request, *args, **kwargs):
        return super(ProdutoListAPI, self).get(self, request, *args, **kwargs)

    def get_queryset(self):
        descricao = self.request.POST.dict().get('descricao')
        
        return Produto.objects.filter(descricao__icontains=descricao)

class CategoriaCreate(SuccessMessageMixin, CreateView):
    model = Categoria
    fields = ['descricao']
    template_name = 'adicionar_categoria_form.html'
    success_message = 'Categoria cadastrada com sucesso!'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return __dispatch__(self, CategoriaCreate, *args, **kwargs)

class CategoriaUpdate(SuccessMessageMixin, UpdateView):
    model = Categoria
    fields = ['descricao']
    template_name = 'detalhe_categoria_form.html'
    success_message = 'Categoria alterada com sucesso!'

    def get_success_url(self):
        return reverse('estoque:categoria-alterar', kwargs=self.kwargs)
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return __dispatch__(self, CategoriaUpdate, *args, **kwargs)

class CategoriaList(ListView):
    model = Categoria
    template_name = 'pesquisar_categoria_form.html'
    paginate_by = 8

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return __dispatch__(self, CategoriaList, *args, **kwargs)

def __dispatch__(self, classView, *args, **kwargs):
    return super(classView, self).dispatch( *args, **kwargs) 

estoque/templates/adicionar_categoria_form.html
{% extends 'easy2make/templates/base.html' %}

{% load bootstrap3 %}

{% block content %}

    <div class="row" style="padding-bottom: 1rem;">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'estoque:categoria-pesquisar' %}">Categoria</a></li>
            <li class="breadcrumb-item"><a href="#">Cadastrar</a></li>
        </ol>
    </div>

    <form action="{% url 'estoque:categoria-adicionar' %}" role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            {% bootstrap_button "Salvar" button_type="submit" button_class="btn-primary" %}
            {% bootstrap_button "Cancelar" button_type="reset" button_class="btn-primary" %}
        {% endbuttons %}
    </form>

{% endblock %}

estoque/templates/adicionar_produto_form.html
{% extends 'easy2make/templates/base.html' %}

{% load bootstrap3 %}

{% block content %}

    <div class="row" style="padding-bottom: 1rem;">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'estoque:produto-pesquisar' %}">Produto</a></li>
            <li class="breadcrumb-item"><a href="#">Cadastrar</a></li>
        </ol>
    </div>

    <form action="{% url 'estoque:produto-adicionar' %}" enctype="multipart/form-data" role="form" method="post">
        {% csrf_token %}
        
        {% bootstrap_form form %}
        
        {% buttons %}
            {% bootstrap_button "Salvar" button_type="submit" button_class="btn-primary" %}
            {% bootstrap_button "Cancelar" button_type="reset" button_class="btn-primary" %}
        {% endbuttons %}
    </form>

{% endblock %}

estoque/templates/detalhe_categoria_form.html
{% extends 'easy2make/templates/base.html' %}

{% load bootstrap3 %}

{% block content %}

    <div class="row" style="padding-bottom: 1rem;">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'estoque:categoria-pesquisar' %}">Categoria</a></li>
            <li class="breadcrumb-item"><a href="#">Alterar</a></li>
            <li class="breadcrumb-item"><a href="#">{{ categoria.descricao }}</a></li>
        </ol>
    </div>

    <form action="{% url 'estoque:categoria-alterar' categoria.id %}" role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            {% bootstrap_button "Salvar" button_type="submit" button_class="btn-primary" %}
            {% bootstrap_button "Cancelar" button_type="reset" button_class="btn-primary" %}
        {% endbuttons %}
    </form>

{% endblock %}

estoque/templates/detalhe_produto_form.html
{% extends 'easy2make/templates/base.html' %}

{% load bootstrap3 %}

{% block content %}

    <div class="row" style="padding-bottom: 1rem;">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'estoque:produto-pesquisar' %}">Produto</a></li>
            <li class="breadcrumb-item"><a href="#">Alterar</a></li>
            <li class="breadcrumb-item"><a href="#">{{ produto.descricao }}</a></li>
        </ol>
    </div>

    <form action="{% url 'estoque:produto-alterar' produto.id %}" enctype="multipart/form-data" role="form" method="post">
        {% csrf_token %}
        
        {% for field in form %}
            {% bootstrap_field field %}
        {% endfor %}
        
        {% buttons %}
            {% bootstrap_button "Salvar" button_type="submit" button_class="btn-primary" %}
            {% bootstrap_button "Cancelar" button_type="reset" button_class="btn-primary" %}
        {% endbuttons %}
    </form>

{% endblock %}

estoque/templates/pesquisar_categoria_form.html
{% extends 'easy2make/templates/base.html' %}

{% load bootstrap3 %}

{% block content %}
    
    <div class="row" style="padding-bottom: 1rem;">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'estoque:categoria-pesquisar' %}">Categoria</a></li>        </ol>
    </div>
   
    <a href="{% url 'estoque:categoria-adicionar' %}" >
            <button style="margin-bottom: 15px;" class="btn btn-primary">
                    Cadastrar
            </button>                
    </a>
 
    {% if object_list %}
        <table class="table table-bordered">
            <tr>
                <th>Descrição</th>
                <th></th>
            </tr>
            {% for object in object_list %}
            <tr>
                <td>{{object.descricao}}</td>
                <td>
                    <a href="{% url 'estoque:categoria-alterar' object.id %}">
                        Detalhes
                    </a>
                </td>  
            </tr>
            {% endfor %}
        </table>
    {% endif %}

    {% include 'easy2make/templates/paginated.html' %}


{% endblock %}

estoque/templates/pesquisar_produto_form.html
{% extends 'easy2make/templates/base.html' %}

{% load bootstrap3 %}

{% block content %}

    <div class="row" style="padding-bottom: 1rem;">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'estoque:produto-pesquisar' %}">Produto</a></li>
            <li class="breadcrumb-item"><a href="#">Pesquisar</a></li>
        </ol>
    </div>
    <form action="{% url 'estoque:produto-pesquisar' %}" role="form" method="get">
        {% csrf_token %}
        
        {% for field in form %}
            {% bootstrap_field field %}
        {% endfor %}
        
        {% buttons %}
            {% bootstrap_button "Pesquisar" button_type="submit" button_class="btn-primary" %}
            
            <a href="{% url 'estoque:produto-adicionar' %}" >
                    <button type="button" class="btn btn-primary">
                            Cadastrar
                    </button>                
            </a>
        {% endbuttons %}

    </form>

    {% if  object_list %}    

        <table class="table table-bordered">
            <tr>
                <th>Descrição</th>
                <th>Preço</th>
                <th>Quantidade</th>
                <th></th>
            </tr>
            {% for object in object_list %}
            <tr>
                <td>{{object.descricao}}</td>
                <td>{{object.preco}}</td>
                <td>{{object.quantidade}}</td>
                <td>
                    <a href="{% url 'estoque:produto-alterar' object.id %}">
                        Detalhes
                    </a>
                </td>  
            </tr>
            {% endfor %}
        </table>

    {% endif %}


    {% include 'easy2make/templates/paginated.html' %}


{% endblock %}