clientes/urls.py
from django.urls import path, include
from .views import ClienteCreate, ClienteUpdate, ClienteList, ClienteListAPI

urlpatterns = [
    path('adicionar/', ClienteCreate.as_view(), name='cliente-adicionar'),
    path('alterar/<int:pk>/', ClienteUpdate.as_view(), name='cliente-alterar'),
    path('pesquisar/', ClienteList.as_view(), name='cliente-pesquisar'),
    path('', ClienteListAPI.as_view())
]

easy2make/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('estoque/', include(('estoque.urls', 'estoque'), namespace='estoque')),
    path('clientes/', include(('clientes.urls', 'clientes'), namespace='clientes')),
    path('vendas/', include(('vendas.urls', 'vendas'), namespace='vendas')),
    path('auth/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

vendas/urls.py
from django.urls import path, include
from .views import VendaList, VendaCreateForm, VendaDetail, VendaCupomDetail, VendaUpdateAPI, ItemVendaUpdateAPI, ItemVendaDeleteAPI, VendaCreateAPI, ItemVendaCreateAPI, VendaDeleteAPI

urlpatterns = [
    path('', VendaCreateForm.as_view(), name='vendas-create-form'),
    path('pesquisar/', VendaList.as_view(), name='vendas-pesquisar'),
    path('<int:pk>/', VendaDetail.as_view(), name='vendas-detalhe'),
    path('<int:pk>/cupom/', VendaCupomDetail.as_view()),
    path('adicionar/', VendaCreateAPI.as_view()),
    path('remover/<int:pk>/', VendaDeleteAPI.as_view()),
    path('alterar/<int:pk>/', VendaUpdateAPI.as_view()),
    path('itens/adicionar/', ItemVendaCreateAPI.as_view()),
    path('itens/remover/<int:pk>/', ItemVendaDeleteAPI.as_view()),
    path('itens/alterar/<int:pk>/', ItemVendaUpdateAPI.as_view())
]

clientes/models.py
from django.db import models
from django.shortcuts import reverse
from django.core.validators import RegexValidator


class Cliente(models.Model):

    nome = models.CharField(max_length=255, blank=False)
    telefone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$')
    telefone = models.CharField(validators=[telefone_regex], max_length=17, blank=True)
    endereco = models.CharField(max_length=255, blank=False)

    def get_absolute_url(self):
        return reverse('clientes:cliente-pesquisar')

clientes/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import DetailView, ListView
from .models import Cliente
from search_views.search import SearchListView
from search_views.filters import BaseFilter
from django.contrib.messages.views import SuccessMessageMixin
from json_views.views import JSONListView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

class ClienteCreate(SuccessMessageMixin, CreateView):
    model = Cliente
    fields = ['nome','telefone','endereco']
    template_name = 'adicionar_cliente_form.html'
    success_message = 'Cliente cadastrado com sucesso!'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return __dispatch__(self, ClienteCreate, *args, **kwargs)


class ClienteUpdate(SuccessMessageMixin, UpdateView):
    model = Cliente
    fields = ['nome','telefone','endereco']
    template_name = 'detalhe_cliente_form.html'
    success_message = 'Cliente alterado com sucesso!'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return __dispatch__(self, ClienteUpdate, *args, **kwargs)


class ClienteFilter(BaseFilter):
    search_fields = {
        'nome' : ['nome'],          
    }

class ClienteList(SearchListView):
    model = Cliente
    paginate_by = 8
    template_name = 'pesquisar_cliente_form.html'
    filter_class = ClienteFilter

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return __dispatch__(self, ClienteList, *args, **kwargs)

class ClienteListAPI(JSONListView):
    model = Cliente
    
    def post(self, request, *args, **kwargs):
        return super(ClienteListAPI, self).get(self, request, *args, **kwargs)

    def get_queryset(self):
        nome = self.request.POST.dict().get('nome')
        return Cliente.objects.filter(nome__icontains=nome)

def __dispatch__(self, classView, *args, **kwargs):
    return super(classView, self).dispatch( *args, **kwargs) 
        

clientes/templates/adicionar_cliente_form.html
{% extends 'easy2make/templates/base.html' %}

{% load bootstrap3 %}

{% block content %}
    
 <div class="row" style="padding-bottom: 1rem;">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'clientes:cliente-pesquisar' %}">Clientes</a></li>
            <li class="breadcrumb-item"><a href="#">Cadastro</a></li>
        </ol>
    </div> 
    <form action="{% url 'clientes:cliente-adicionar' %}" role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            {% bootstrap_button "Salvar" button_type="submit" button_class="btn-primary" %}
            {% bootstrap_button "Cancelar" button_type="reset" button_class="btn-primary" %}
        {% endbuttons %}
    </form>

{% endblock %}

clientes/templates/detalhe_cliente_form.html
{% extends 'easy2make/templates/base.html' %}

{% load bootstrap3 %}

{% block content %}
    
<div class="row" style="padding-bottom: 1rem;">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'clientes:cliente-pesquisar' %}">Clientes</a></li>
            <li class="breadcrumb-item"><a href="#">Alterar</a></li>
            <li class="breadcrumb-item"><a href="#">{{cliente.nome}}</a></li>
        </ol>
    </div>

    <form action="{% url 'clientes:cliente-alterar' cliente.id %}" role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            {% bootstrap_button "Salvar" button_type="submit" button_class="btn-primary" %}
            {% bootstrap_button "Cancelar" button_type="reset" button_class="btn-primary" %}
        {% endbuttons %}
    </form>

    {% if cliente.compras.all %}
    <table class="table">
        
        <thead>

            <tr>
                <th colspan="3">Compras</th> 
            </tr>

            <tr>
                <th>Data</th>
                <th>Situação</th>
            </tr>

        </thead>

        {% for compra in cliente.compras.all %}

        <tr>
            <td>{{compra.data | date:'d/m/y' }}</td>
            <td>
                {% if compra.situacao == 'P' %}
                    PENDENTE
                {% else %}
                    FINALIZADA
                {% endif %}
            </td>
            <td>
                <a href="{% url 'vendas:vendas-detalhe' compra.id %}">
                    Detalhes
                </a>
            </td>
        </tr>


        {% endfor %}

    </table>
    {% endif %}

{% endblock %}

clientes/templates/pesquisar_cliente_form.html
{% extends 'easy2make/templates/base.html' %}

{% load bootstrap3 %}

{% block content %}
    <div class="row" style="padding-bottom: 1rem;">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'clientes:cliente-pesquisar' %}">Clientes</a></li>
            <li class="breadcrumb-item"><a href="#">Pesquisar</a></li>
        </ol>
    </div>
   
    <a href="{% url 'clientes:cliente-adicionar' %}" >
            <button style="margin-bottom: 15px;" class="btn btn-primary">
                    Cadastrar
            </button>                
    </a>
    
    {% if  object_list %}

        <table class="table table-bordered">
            <tr>
                <th>Nome</th>
                <th></th>
            </tr>
            {% for object in object_list %}
            <tr>
                <td>{{object.nome}}</td>
                <td>
                    <a href="{% url 'clientes:cliente-alterar' object.id %}">
                        Detalhes
                    </a>
                </td>  
            </tr>
            {% endfor %}
        </table>

    {% endif %}

{% include "easy2make/templates/paginated.html" %}


{% endblock %}